### ISSUE TITLE
Deploy initial clinvar-ftp-watcher production version

### ISSUE THREAD

**Issue by toneillbroad** [clingen-data-model/clinvar-ftp-watcher#1]
Epic that covers the initial production deployment of clinvar ftp watchar

**Comment by larrybabb** [comment]
@toneillbroad Can you provide a status on this epic at today's standup?  If the remaining "new issues" are not required for the near term, then let's break them out into a future epic that we can put in the backlog or icebox. It would be nice to get closure on this.
